import {chromium,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:4178/sam-digital/';
const browser=await chromium.launch({channel:'chrome',headless:true});
const ctx=await browser.newContext({viewport:{width:1440,height:1000}});const checks=[];
await mkdir('proof/concierge',{recursive:true});
// Explicit UI-only fixture. This does NOT count as real-model evidence.
await ctx.route('**/assets/atmosphere-*.js',r=>r.fulfill({contentType:'text/javascript',body:'export function startAtmosphere(host){host.dataset.renderer="test-fixture";}'}));
await ctx.addInitScript(()=>{
 Object.defineProperty(navigator,'gpu',{value:{},configurable:true});Object.defineProperty(window,'LanguageModel',{value:undefined,configurable:true});
 window.__messages=[];window.Worker=class{constructor(){window.__worker=this;}postMessage(d){window.__messages.push(d);if(d.type==='init')queueMicrotask(()=>this.onmessage({data:{type:'progress',text:'Fixture model loading',progress:.25}}));}terminate(){}emit(data){this.onmessage({data});}};
});
const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function check(name,fn){const evidence=await fn();checks.push({name,pass:true,evidence});console.log('PASS',name,JSON.stringify(evidence??''));}
async function ready(){await page.evaluate(()=>window.__worker.emit({type:'ready',model:'Explicit test fixture'}));}
async function complete(){await expect.poll(()=>page.evaluate(()=>window.__messages.filter(m=>m.type==='generate').length)).toBeGreaterThan(0);await page.evaluate(()=>{const id=window.__messages.filter(m=>m.type==='generate').at(-1).id;window.__worker.emit({type:'delta',id,text:'Fixture response for state-machine testing.'});window.__worker.emit({type:'done',id});});}
try{
 await page.goto(base,{waitUntil:'domcontentloaded'});
 await check('Model initialization starts before the independent two-second intro ends',async()=>{await expect.poll(()=>page.evaluate(()=>window.__messages.some(m=>m.type==='init'))).toBe(true);await expect(page.locator('#intro')).toHaveCount(0,{timeout:4000});const marks=await page.evaluate(()=>Object.fromEntries(performance.getEntriesByType('mark').map(m=>[m.name,m.startTime])));expect(marks['model-init']).toBeLessThan(marks['intro-end']);const duration=marks['intro-end']-marks['intro-start'];expect(duration).toBeGreaterThanOrEqual(1900);expect(duration).toBeLessThan(2800);return {durationMs:duration,modelInitMs:marks['model-init']};});
 await check('Typing is available while the model is still preparing',async()=>{await expect(page.locator('body')).toHaveAttribute('data-model','preparing');await page.locator('#prompt').fill('A test enquiry');await expect(page.locator('#prompt')).toHaveValue('A test enquiry');});
 await check('Queued request shows exact Researching message and synapse state',async()=>{await page.locator('#composer').evaluate(f=>f.requestSubmit());await expect(page.getByText('Researching your request',{exact:true})).toBeVisible();await expect(page.locator('.loading-detail')).toContainText('still loading');await expect(page.locator('#atmosphere')).toHaveAttribute('data-state','researching');expect(await page.evaluate(()=>window.__messages.some(m=>m.type==='generate'))).toBe(false);await ready();await complete();await expect(page.locator('.researching')).toBeHidden();await expect(page.locator('#atmosphere')).toHaveAttribute('data-state','engaged');await expect(page.locator('#follow-ups')).toBeVisible();await expect(page.locator('#prompt')).toHaveAttribute('placeholder','');});
 const names=['What do you do?','Can you automate my workflow?','Can you build my app?','How does pricing work?','How do we get started?'];
 for(const name of names)await check(`Common-question button: ${name}`,async()=>{await page.locator('#fresh').click();await page.getByRole('button',{name,exact:true}).click();await expect(page.locator('.turn.user')).toHaveCount(1);await expect(page.getByText('Researching your request',{exact:true})).toBeVisible();await complete();return await page.locator('.turn.user').innerText();});
 await check('Follow-up buttons continue the same conversation',async()=>{const before=await page.locator('.turn.user').count();await page.locator('#follow-ups [data-prompt]').first().click();await complete();await expect(page.locator('.turn.user')).toHaveCount(before+1);});
 await check('Enquiry is editable; mail draft is correctly encoded, not sent',async()=>{await page.locator('#review').click();await page.locator('#brief').fill('Café & automation?\nA+B #1');const href=await page.locator('#email').getAttribute('href');expect(new URL(href).searchParams.get('body')).toBe('Café & automation?\nA+B #1');await page.getByRole('button',{name:'Close enquiry'}).click();});
 await check('Stop during model loading never generates a deferred reply',async()=>{await page.reload({waitUntil:'domcontentloaded'});await page.locator('#prompt').fill('Please help');await page.locator('#composer').evaluate(f=>f.requestSubmit());await page.getByRole('button',{name:'Stop response',exact:true}).click();await ready();await page.waitForTimeout(100);expect(await page.evaluate(()=>window.__messages.some(m=>m.type==='generate'))).toBe(false);});
 await check('Responsive layout has no horizontal overflow',async()=>{const widths=[320,390,768,1440];for(const width of widths){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}return widths;});
 await check('Automated accessibility checks pass',async()=>{await expect(page.locator('#intro')).toHaveCount(0);const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations).toEqual([]);return {violations:results.violations.length};});
 await check('Reduced-motion preference bypasses intro animation',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await expect(page.locator('#intro')).toHaveCount(0);});
 await check('Unsupported browser keeps direct enquiry usable',async()=>{const p=await browser.newPage();await p.addInitScript(()=>{Object.defineProperty(navigator,'gpu',{value:undefined});Object.defineProperty(window,'LanguageModel',{value:undefined});});await p.goto(base);await expect(p.locator('body')).toHaveAttribute('data-model','failed');await p.locator('#review').click();await expect(p.locator('#email')).toHaveAttribute('href',/^mailto:sam-in-nashville@pm.me/);await p.close();});
 await check('No-JavaScript page keeps services and direct contact',async()=>{const c=await browser.newContext({javaScriptEnabled:false});const p=await c.newPage();await p.goto(base);await expect(p.locator('h1')).toHaveText('Sam is here to help you.');await expect(p.locator('#composer')).toBeHidden();await expect(p.locator('noscript a')).toBeVisible();await c.close();});
 await check('No uncaught UI errors',async()=>expect(errors).toEqual([]));
 await writeFile('proof/concierge/ui-results.json',JSON.stringify(checks,null,2));console.log(`${checks.length}/${checks.length} UI checks passed; model responses above are explicit fixtures`);
}finally{await browser.close();}
