import {chromium,expect} from '@playwright/test';import {mkdir,copyFile} from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:4183/sam-digital/';await mkdir('proof/experience/video',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:'proof/experience/video',size:{width:1440,height:1000}}});
await ctx.addInitScript(()=>{window.Worker=class{postMessage(d){if(d.type==='init')queueMicrotask(()=>this.onmessage({data:{type:'ready',model:'Explicit motion fixture'}}));if(d.type==='generate')window.done=()=>{this.onmessage({data:{type:'delta',id:d.id,text:JSON.stringify({reply:'Let’s explore that idea together.',uncertain:false,evidence:{outcome:'',people:'',starting:'',better:''}})}});this.onmessage({data:{type:'done',id:d.id}});};}terminate(){}};});
const page=await ctx.newPage();const signature=()=>page.locator('.neural-overlay').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let sum=0,hash=0;for(let i=3;i<d.length;i+=4){sum+=d[i];hash=(hash+Math.imul(d[i],i))>>>0;}return {sum,hash};});
try{
 await page.goto(base);await expect(page.locator('#atmosphere')).toHaveAttribute('data-renderer','webgpu',{timeout:45000});await expect(page.locator('#intro')).toHaveCount(0);
 expect((await signature()).sum).toBe(0);const idleFrames=await page.locator('#atmosphere').getAttribute('data-neural-frames');await page.waitForTimeout(500);expect(await page.locator('#atmosphere').getAttribute('data-neural-frames')).toBe(idleFrames);
 await page.locator('#prompt').fill('Can we make something people will love using?');await page.locator('#composer').evaluate(f=>f.requestSubmit());await page.waitForTimeout(900);const first=await signature();const pose=await page.locator('#companion').evaluate(e=>getComputedStyle(e).transform);await page.waitForTimeout(800);const second=await signature();expect(first.sum).toBeGreaterThan(0);expect(second.sum).toBeGreaterThan(0);expect(second.hash).not.toBe(first.hash);expect(await page.locator('#companion').evaluate(e=>getComputedStyle(e).transform)).not.toBe(pose);
 await page.waitForTimeout(4000);const longWait=await signature();expect(longWait.sum).toBeGreaterThan(0);
 await page.locator('#motion').click();const frozen=await signature();await page.waitForTimeout(700);expect(await signature()).toEqual(frozen);await page.locator('#motion').click();await page.evaluate(()=>window.done());await page.waitForTimeout(2200);expect((await signature()).sum).toBe(0);
 console.log('PASS real GPU cloud + changing neural pixels + companion movement + long response + frozen pause + full fade + zero idle frame loop');
}finally{const video=page.video();await ctx.close();await copyFile(await video.path(),'proof/experience/neural-companion.webm');await browser.close();}
