import {chromium,expect} from '@playwright/test';
import {writeFile,mkdir} from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:4178/sam-digital/';
const browser=await chromium.launch({channel:'chrome',headless:true});
const results=[];
async function check(name,fn){const evidence=await fn();results.push({name,pass:true,evidence});console.log('PASS',name,JSON.stringify(evidence||''));}
await mkdir('proof/kinetic',{recursive:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();
try{
 await page.goto(base);await expect(page.locator('#signal')).toHaveAttribute('data-renderer','webgpu',{timeout:25000});await page.evaluate(()=>document.fonts.ready);
 await check('Continuous idle rendering without cursor input',async()=>{const count=()=>page.locator('#signal').getAttribute('data-frames').then(Number);const first=await count();const a=await page.locator('#signal-canvas').evaluate(c=>c.toDataURL());await expect.poll(count).toBeGreaterThan(first+12);const b=await page.locator('#signal-canvas').evaluate(c=>c.toDataURL());expect(a).not.toBe(b);await page.screenshot({path:'proof/kinetic/hero-live.png'});return {advancedFrames:(await count())-first};});
 const depths=()=>page.evaluate(()=>({signal:Number(document.querySelector('#signal').dataset.offset),copy:Number(document.querySelector('.hero-copy').dataset.offset),band:new DOMMatrixReadOnly(getComputedStyle(document.querySelector('.kinetic-type')).transform).m41}));
 await check('Independent opposite-direction scroll depth planes',async()=>{await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(150);const a=await depths();await page.evaluate(()=>scrollTo({top:320,behavior:'instant'}));await expect.poll(async()=>Math.abs((await depths()).signal-a.signal)).toBeGreaterThan(20);const b=await depths();expect(b.copy-a.copy).toBeLessThan(-10);expect(b.band-a.band).toBeLessThan(-10);await page.screenshot({path:'proof/kinetic/scroll-320.png'});return {sculptureDelta:b.signal-a.signal,copyDelta:b.copy-a.copy,typographyDelta:b.band-a.band};});
 await check('Native scroll and experience-panel parallax',async()=>{await page.locator('#about').scrollIntoViewIfNeeded();const y=await page.evaluate(()=>scrollY);const before=await page.locator('.about-visual').getAttribute('data-offset').then(Number);await page.mouse.wheel(0,260);await expect.poll(()=>page.evaluate(()=>scrollY)).toBeGreaterThan(y+100);await expect.poll(async()=>Math.abs(Number(await page.locator('.about-visual').getAttribute('data-offset'))-before)).toBeGreaterThan(10);await page.screenshot({path:'proof/kinetic/about-depth.png'});});
 await check('Reduced motion disables parallax and autonomous frames',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await expect(page.locator('#motion-toggle')).toHaveAttribute('aria-pressed','true');await expect.poll(async()=>Number(await page.locator('#signal').getAttribute('data-offset'))).toBe(0);await page.waitForTimeout(200);const n=Number(await page.locator('#signal').getAttribute('data-frames'));await page.waitForTimeout(250);expect(Number(await page.locator('#signal').getAttribute('data-frames'))).toBe(n);});
 await check('No-WebGPU path visibly animates, pauses and resumes',async()=>{const p=await context.newPage();await p.addInitScript(()=>Object.defineProperty(navigator,'gpu',{value:undefined}));await p.goto(base);await expect(p.locator('#signal')).toHaveAttribute('data-renderer','canvas2d');const a=await p.locator('.signal-canvas2d').evaluate(c=>c.toDataURL());await p.waitForTimeout(600);const b=await p.locator('.signal-canvas2d').evaluate(c=>c.toDataURL());expect(a).not.toBe(b);await p.locator('#motion-toggle').click();await p.waitForTimeout(200);const c=await p.locator('.signal-canvas2d').evaluate(c=>c.toDataURL());await p.waitForTimeout(250);expect(await p.locator('.signal-canvas2d').evaluate(c=>c.toDataURL())).toBe(c);await p.screenshot({path:'proof/kinetic/canvas2d.png'});await p.locator('#motion-toggle').click();await p.waitForTimeout(400);expect(await p.locator('.signal-canvas2d').evaluate(c=>c.toDataURL())).not.toBe(c);await p.close();});
 await check('Data saver never requests the WebGPU renderer module',async()=>{const p=await context.newPage();const urls=[];p.on('request',r=>urls.push(r.url()));await p.addInitScript(()=>Object.defineProperty(navigator,'connection',{value:{saveData:true}}));await p.goto(base);await expect(p.locator('#signal')).toHaveAttribute('data-renderer','canvas2d');await p.waitForTimeout(200);expect(urls.some(u=>u.includes('signal-renderer-'))).toBe(false);await p.close();});
 await writeFile('proof/kinetic/results.json',JSON.stringify(results,null,2));console.log(`${results.length}/${results.length} kinetic checks passed`);
}finally{await browser.close();}
