import {chromium,expect} from '@playwright/test';import {mkdir} from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:4183/sam-digital/';await mkdir('proof/pet',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:'proof/pet',size:{width:1440,height:1000}}});
await ctx.addInitScript(()=>{window.Worker=class{postMessage(d){if(d.type==='init')queueMicrotask(()=>this.onmessage({data:{type:'ready',model:'Explicit pet fixture'}}));}terminate(){}};});
const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(base);await expect(page.locator('#intro')).toHaveCount(0);await expect(page.locator('.dot-flight #companion')).toBeVisible();await expect(page.locator('.dot-jetpack')).toHaveCount(1);
 let moves=0;const start=await page.locator('.dot-flight').boundingBox();await expect.poll(async()=>{await page.mouse.move(1100+(++moves%2)*10,220);return page.locator('.dot-flight').getAttribute('data-reason');},{timeout:10000,intervals:[500]}).toBe('curious');await page.waitForTimeout(600);await expect(page.locator('.dot-flight')).toHaveAttribute('data-flying','true');expect(await page.locator('.dot-exhaust').evaluate(e=>Number(getComputedStyle(e).opacity))).toBeGreaterThan(0);await page.screenshot({path:'proof/pet/jetpack-flight.png'});await page.waitForTimeout(1200);const moved=await page.locator('.dot-flight').boundingBox();expect(Math.hypot(moved.x-start.x,moved.y-start.y)).toBeGreaterThan(80);
 await page.locator('#prompt').focus();await expect(page.locator('.dot-flight')).toHaveAttribute('data-reason','focus');await page.keyboard.type('A quiet idea');await expect(page.locator('#prompt')).toBeFocused();await page.waitForTimeout(2000);expect(await page.locator('.dot-bubble').isVisible()).toBe(false);
 await page.locator('#prompt').evaluate(e=>e.blur());await page.waitForTimeout(19000);await expect(page.locator('.dot-flight')).toHaveAttribute('data-reason','idle');await page.waitForTimeout(1800);await expect(page.locator('#prompt')).toHaveClass(/dot-invite/);await expect(page.locator('.dot-bubble')).toContainText('Your next idea');await expect(page.locator('#prompt')).not.toBeFocused();await page.screenshot({path:'proof/pet/idle-invitation.png'});
 await page.locator('#motion').click();await expect(page.locator('#companion-stage #companion')).toBeVisible();await expect(page.locator('.dot-flight')).toBeHidden();await page.locator('#motion').click();await expect(page.locator('.dot-flight #companion')).toBeVisible();
 await page.locator('#companion-toggle').click();await expect(page.locator('#companion')).toBeHidden();await expect(page.locator('.dot-flight')).toBeHidden();await page.locator('#companion-toggle').click();await expect(page.locator('#companion')).toBeVisible();
 await page.locator('#review').click();await expect(page.locator('.dot-flight')).toBeHidden();await page.locator('.close').click();await expect(page.locator('.dot-flight')).toBeVisible();
 await page.locator('#showcase').scrollIntoViewIfNeeded();await page.waitForTimeout(500);await page.locator('[data-palette=lavender]').focus();await page.waitForTimeout(2000);await page.screenshot({path:'proof/pet/gallery-curiosity.png'});await expect(page.locator('[data-palette=lavender]')).toBeFocused();
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(500);await page.screenshot({path:'proof/pet/mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const overlaps=await page.evaluate(()=>{const a=document.querySelector('#companion').getBoundingClientRect();return [...document.querySelectorAll('h1,.lede,#composer')].some(e=>{const b=e.getBoundingClientRect();return a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;});});expect(overlaps).toBe(false);
 await page.emulateMedia({reducedMotion:'reduce'});await expect(page.locator('.dot-flight')).toBeHidden();await expect(page.locator('#companion-stage #companion')).toBeVisible();expect(errors).toEqual([]);
 console.log('PASS jetpack, roaming, mouse curiosity, focus, idle invitation without focus theft, hide, pause, dialog suppression and mobile/reduced motion');
}finally{const video=page.video();await ctx.close();await video.saveAs('proof/pet/roaming.webm');await browser.close();}
