// Local choreography only: observes element focus and pointer position, never field values.
export function roamPet(stage,pet){
 const flight=document.createElement('div');flight.className='dot-flight';flight.setAttribute('aria-hidden','true');flight.dataset.mood=stage.dataset.mood||'idle';
 const bubble=document.createElement('div');bubble.className='dot-bubble';bubble.setAttribute('aria-hidden','true');bubble.hidden=true;flight.append(pet);document.body.append(flight,bubble);
 const svg=pet.querySelector('svg');svg.insertAdjacentHTML('afterbegin','<g class="dot-jetpack"><rect x="10" y="48" width="15" height="32" rx="6" fill="#55768f" stroke="#c4eee4"/><rect x="75" y="48" width="15" height="32" rx="6" fill="#55768f" stroke="#c4eee4"/><path class="dot-exhaust" d="M12 80Q10 103 18 123Q26 103 23 80ZM77 80Q75 103 83 123Q91 103 88 80Z" fill="#73cdfa"/><path class="dot-exhaust-core" d="M15 80L18 108 21 80M80 80L83 108 86 80" fill="#f0fff9"/></g>');
 svg.insertAdjacentHTML('beforeend','<g class="dot-point"><path d="M77 64L93 57M87 53L94 57 91 64" stroke="#d7fff2" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></g>');
 let lastActivity=performance.now(),lastTrip=0,lastBubble=-1e9,idleHinted=false,trip=0,x=0,y=0,landing,flightAnimation,bubbleTimer,scrollTimer,disposed=false;
 const input=document.querySelector('#prompt');const active=()=>!disposed&&!pet.hidden&&stage.dataset.still!=='true'&&!document.hidden&&!document.querySelector('dialog[open]');
 const visible=r=>r.width>0&&r.height>0&&r.bottom>8&&r.top<innerHeight-8;
 const obstacles=()=>[...document.querySelectorAll('header,#composer,.turn,.showcase-card,button,a,input,textarea,select,summary,h1,h2,h3,p,.ai-introduction>div:last-child,.privacy,dialog[open]')].filter(e=>!e.closest('#companion-stage')&&!e.closest('.dot-flight')&&!e.closest('.dot-bubble')).map(e=>e.getBoundingClientRect()).filter(visible);
 const fits=(r,blocks)=>r.x>=8&&r.y>=8&&r.x+r.w<=innerWidth-8&&r.y+r.h<=innerHeight-8&&!blocks.some(b=>r.x<b.right+7&&r.x+r.w>b.left-7&&r.y<b.bottom+7&&r.y+r.h>b.top-7);
 function spot(target,away=false){const blocks=obstacles(),points=[];const home=stage.getBoundingClientRect();if(visible(home))points.push({x:home.left+10,y:home.top});for(let yy=70;yy<innerHeight-100;yy+=60)for(const xx of [12,innerWidth-94,innerWidth*.24,innerWidth*.72])points.push({x:xx,y:yy});const candidates=points.filter(p=>fits({...p,w:82,h:98},blocks));const tx=target?.x??innerWidth/2,ty=target?.y??innerHeight/2;return candidates.sort((a,b)=>{const cost=p=>Math.hypot(p.x-tx,p.y-ty)+(away&&Math.hypot(p.x-x,p.y-y)<100?1000:0);return cost(a)-cost(b);})[0];}

 // Visibility graph around padded text/control rectangles: never fly through them.
 function route(start,end){
  const blocks=obstacles();const valid=p=>fits({...p,w:82,h:98},blocks);
  const clear=(a,b)=>!blocks.some(r=>{let lo=0,hi=1;for(const [v,d,min,max] of [[a.x,b.x-a.x,r.left-89,r.right+7],[a.y,b.y-a.y,r.top-105,r.bottom+7]]){if(Math.abs(d)<.001){if(v<=min||v>=max)return false;continue;}const t1=(min-v)/d,t2=(max-v)/d;lo=Math.max(lo,Math.min(t1,t2));hi=Math.min(hi,Math.max(t1,t2));if(lo>=hi)return false;}return hi>0&&lo<1;});
  if(clear(start,end))return [start,end];
  const nodes=[start,end,...blocks.flatMap(r=>[{x:r.left-90,y:r.top-106},{x:r.right+8,y:r.top-106},{x:r.left-90,y:r.bottom+8},{x:r.right+8,y:r.bottom+8}]).filter(valid)];
  const costs=nodes.map(()=>Infinity),previous=[],done=new Set();costs[0]=0;
  while(done.size<nodes.length){let current=-1;for(let i=0;i<nodes.length;i++)if(!done.has(i)&&(current<0||costs[i]<costs[current]))current=i;if(current<0||!Number.isFinite(costs[current]))break;if(current===1){const path=[];for(let i=1;i!==undefined;i=previous[i])path.unshift(nodes[i]);return path;}done.add(current);for(let j=0;j<nodes.length;j++){if(done.has(j))continue;const distance=Math.hypot(nodes[j].x-nodes[current].x,nodes[j].y-nodes[current].y);if(costs[current]+distance<costs[j]&&clear(nodes[current],nodes[j])){costs[j]=costs[current]+distance;previous[j]=current;}}}
  return null;
 }
 function hush(){bubble.hidden=true;clearTimeout(bubbleTimer);flight.dataset.point='false';input?.classList.remove('dot-invite');}
 function say(text){if(!active()||performance.now()-lastBubble<20000)return;const blocks=obstacles();const w=Math.min(184,innerWidth-20),h=66;const choices=[{x:x+88,y},{x:x-w-8,y},{x:x-w/2+35,y:y-76},{x:x-w/2+35,y:y+102}];const place=choices.find(p=>fits({...p,w,h},blocks));if(!place)return;bubble.textContent=text;bubble.style.left=place.x+'px';bubble.style.top=place.y+'px';bubble.hidden=false;lastBubble=performance.now();bubbleTimer=setTimeout(hush,5000);}
 function move(target,reason='explore',instant=false){if(!active())return;const place=spot(target,reason==='explore');if(!place){flight.hidden=true;return;}const current=flight.getBoundingClientRect();const start={x:current.left,y:current.top};const path=instant?[place]:route(start,place);if(!path)return;flight.hidden=false;hush();clearTimeout(landing);flightAnimation?.cancel();flight.dataset.flying=String(!instant);flight.dataset.reason=reason;flight.style.setProperty('--lean',place.x>x?'8deg':'-8deg');x=place.x;y=place.y;flight.style.transform=`translate3d(${x}px,${y}px,0)`;lastTrip=performance.now();let duration=0;if(!instant){let length=0;const distances=[0];for(let i=1;i<path.length;i++){length+=Math.hypot(path[i].x-path[i-1].x,path[i].y-path[i-1].y);distances.push(length);}duration=Math.max(900,Math.min(3500,length*2.5));flightAnimation=flight.animate(path.map((p,i)=>({transform:`translate3d(${p.x}px,${p.y}px,0)`,offset:length?distances[i]/length:i/(path.length-1)})),{duration,easing:'ease-in-out'});}landing=setTimeout(()=>{flight.dataset.flying='false';if(target){pet.style.setProperty('--look-x',`${Math.max(-3,Math.min(3,(target.x-x-41)/80))}px`);pet.style.setProperty('--look-y',`${Math.max(-2,Math.min(2,(target.y-y-40)/100))}px`);}if(reason==='idle'){flight.dataset.point='true';input?.classList.add('dot-invite');say('Your next idea can start here.');lookAtInput();}},duration);}

 function lookAtInput(){const r=input?.getBoundingClientRect();if(!r)return;flight.style.setProperty('--point-angle',`${Math.atan2(r.top+r.height/2-y-50,r.left+r.width/2-x-60)*180/Math.PI+23}deg`);pet.style.setProperty('--look-x',r.left+r.width/2>x?'3px':'-3px');pet.style.setProperty('--look-y','2px');}
 function activity(){lastActivity=performance.now();hush();}
 function focus(e){activity();if(!active())return;const r=e.target.getBoundingClientRect?.();if(!r)return;move({x:r.left+r.width/2,y:r.top+r.height/2},'focus');if(e.target.closest('#showcase'))setTimeout(()=>say(e.target.closest('.design-study')?'A new coat of paint?':'A tiny arcade detour.'),1700);}
 function pointer(e){if(!active()||e.pointerType==='touch')return;lastActivity=performance.now();if(performance.now()-lastTrip>6000&&document.activeElement!==input)move({x:e.clientX,y:e.clientY},'curious');}
 function sync(){flight.dataset.still=stage.dataset.still||'false';flight.dataset.mood=stage.dataset.mood||'idle';if(!active()){hush();flightAnimation?.cancel();flight.dataset.flying='false';clearTimeout(landing);flight.hidden=true;if(pet.parentNode!==stage)stage.prepend(pet);}else{if(pet.parentNode!==flight)flight.prepend(pet);flight.hidden=false;move(null,'return',true);}}
 const moodObserver=new MutationObserver(()=>{if(stage.dataset.still==='true'||pet.hidden||pet.parentNode!==flight){sync();return;}flight.dataset.mood=stage.dataset.mood||'idle';if(flight.dataset.mood==='thinking'){hush();const r=input.getBoundingClientRect();move({x:r.left,y:r.top},'thinking');}else if(flight.dataset.mood==='reply')say('Something to explore together.');});moodObserver.observe(stage,{attributes:true,attributeFilter:['data-mood','data-still']});
 const hiddenObserver=new MutationObserver(sync);hiddenObserver.observe(pet,{attributes:true,attributeFilter:['hidden']});
 const tick=setInterval(()=>{if(!active())return;const now=performance.now(),r=input?.getBoundingClientRect();if(!idleHinted&&now-lastActivity>18000&&r&&visible(r)&&document.activeElement!==input&&stage.dataset.mood==='idle'){idleHinted=true;move({x:r.left+r.width/2,y:r.top},'idle');return;}if(now-lastTrip>10000&&stage.dataset.mood==='idle'&&document.activeElement!==input){const side=++trip%2;move({x:side?innerWidth-90:40,y:100+(trip%4)*innerHeight*.17},'explore');}},1500);
 function scroll(){hush();flightAnimation?.cancel();clearTimeout(landing);clearTimeout(scrollTimer);flight.hidden=true;scrollTimer=setTimeout(()=>move(null,'scroll',true),160);}
 document.addEventListener('focusin',focus);document.addEventListener('pointermove',pointer,{passive:true});document.addEventListener('keydown',activity);document.addEventListener('pointerdown',activity);document.addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);document.addEventListener('visibilitychange',sync);document.addEventListener('toggle',sync,true);
 addEventListener('pagehide',()=>{disposed=true;hush();flightAnimation?.cancel();clearTimeout(landing);clearTimeout(scrollTimer);flight.hidden=true;});addEventListener('pageshow',()=>{disposed=false;lastActivity=performance.now();sync();});sync();
 return ()=>{clearInterval(tick);clearTimeout(landing);clearTimeout(scrollTimer);hush();moodObserver.disconnect();hiddenObserver.disconnect();stage.prepend(pet);flight.remove();bubble.remove();document.removeEventListener('focusin',focus);document.removeEventListener('pointermove',pointer);document.removeEventListener('keydown',activity);document.removeEventListener('pointerdown',activity);document.removeEventListener('scroll',scroll);removeEventListener('resize',scroll);document.removeEventListener('visibilitychange',sync);document.removeEventListener('toggle',sync,true);};
}
