// Owner-controlled answers for the questions the site itself invites visitors to ask.
// These are company guidance, not model-generated pricing or delivery commitments.
export const STARTERS=[
 {id:'services',label:'What can you help with?',prompt:'What services does Sam Digital offer?',answer:'I help with games, websites, apps, repetitive work, research and clear instructions. That can mean bringing an idea to life, fixing something frustrating, or making it easier for customers to reach you. What would you like to make better?'},
 {id:'build',label:'Build something new',prompt:'Can you help me build something new?',answer:'I can help turn an idea into a game, website or app—or improve something you already have. You don’t need to know how it should be built. What would you like someone to be able to do?'},
 {id:'simplify',label:'Make repetitive work easier',prompt:'Can you help me spend less time on repetitive work?',answer:'I can help simplify work like copying information, preparing routine reports or keeping track of requests. Start with the part that eats up your time. What do you find yourself doing over and over?'},
 {id:'research',label:'Help me make a decision',prompt:'Can you help me understand something before I make a decision?',answer:'I can help with research and analysis to make a decision clearer. Here, we can talk through what you need to understand; a research request can then go to a human. This chat doesn’t look up live information. What decision are you trying to make?'},
 {id:'writing',label:'Make instructions clearer',prompt:'Can you help make instructions easier for people to follow?',answer:'I can help with instructions, guides and documentation that people can actually use. You don’t need to send a document here—just describe where people get stuck. What are they trying to do?'},
 {id:'pricing',label:'How does pricing work?',prompt:'How does your pricing work?',answer:'Start by describing what you want to achieve. Send Request lets you review the conversation and email it for a human discussion of the work and pricing. This chat doesn’t set prices, provide estimates or promise a fixed quote. You don’t need a budget figured out to begin.'},
 {id:'start',label:'How do we get started?',prompt:'How do we get started on a project?',answer:'Tell me what you want to accomplish and what happens today. We can explore the useful details together, then Send Request lets you review the whole conversation and email it to a human. You can do that whenever you’re ready. What would you like to make possible?'}
];
const normalize=s=>s.toLowerCase().replace(/[?!.]/g,'').replace(/\s+/g,' ').trim();
export function starterAnswer(text){const value=normalize(text);return STARTERS.find(s=>normalize(s.prompt)===value||normalize(s.label)===value)?.answer||null;}
