import './arcade.css';

const W = 640;
const H = 390;
const MAX_PARTICLES = 140;

const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const circleHitsRect = (ball, rect) => ball.x + ball.r > rect.x && ball.x - ball.r < rect.x + rect.w && ball.y + ball.r > rect.y && ball.y - ball.r < rect.y + rect.h;

export function mount(host) {
  if (!(host instanceof HTMLElement)) throw new TypeError('mount(host) expects an HTMLElement');
  host.replaceChildren();
  const root = document.createElement('section');
  root.className = 'arcade-demo';
  root.dataset.gameState = 'ready';
  root.dataset.score = '0';
  root.dataset.frames = '0';
  root.innerHTML = `
    <header class="arcade-demo__header"><div><p class="arcade-demo__eyebrow">Playable experiment / 01</p><h2>Neon Breakout</h2><p>Clear the signal wall. Every bounce is simulated locally, with momentum, score, lives and a little light left behind.</p></div><label class="arcade-demo__difficulty">Difficulty <select data-difficulty aria-label="Game difficulty"><option value="0.9">Soft launch</option><option value="1.15" selected>Studio pace</option><option value="1.4">Full signal</option></select></label></header>
    <div class="arcade-demo__stage"><canvas data-game-canvas tabindex="0" aria-label="Neon Breakout game. Use left and right arrow keys, A and D, or drag on the game field to move the paddle."></canvas><div class="arcade-demo__scanline" aria-hidden="true"></div></div>
    <div class="arcade-demo__bar"><div class="arcade-demo__buttons"><button type="button" data-start>Start game</button><button type="button" data-pause disabled>Pause</button><button type="button" data-restart>Restart</button></div><div class="arcade-demo__stats" aria-label="Game statistics"><span>Score <b data-score-readout>0</b></span><span>Lives <b data-lives>3</b></span><span>Best <b data-best>0</b></span></div></div>
    <p class="arcade-demo__status" data-status role="status" aria-live="polite">Ready when you are.</p>
  `;
  host.append(root);
  const canvas = root.querySelector('[data-game-canvas]');
  const ctx = canvas.getContext('2d');
  const startButton = root.querySelector('[data-start]');
  const pauseButton = root.querySelector('[data-pause]');
  const status = root.querySelector('[data-status]');
  const scoreReadout = root.querySelector('[data-score-readout]');
  const livesReadout = root.querySelector('[data-lives]');
  const bestReadout = root.querySelector('[data-best]');
  const difficulty = root.querySelector('[data-difficulty]');
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const game = { score: 0, best: 0, lives: 3, running: false, paused: false, hidden: false, frames: 0, raf: 0, last: 0, width: W, height: H, paddle: { x: 270, y: 357, w: 100, h: 12 }, ball: { x: 320, y: 330, r: 7, vx: 190, vy: -235 }, bricks: [], particles: [], trail: [] };
  let disposed = false;
  const setStatus = (text) => { status.textContent = text; };
  const updateData = () => { pauseButton.textContent=game.paused?'Resume':'Pause'; scoreReadout.textContent = game.score; livesReadout.textContent = game.lives; bestReadout.textContent = game.best; root.dataset.score = game.score; root.dataset.frames = game.frames; root.dataset.ballX=game.ball.x;root.dataset.ballY=game.ball.y;root.dataset.paddleX=game.paddle.x;root.dataset.paddleWidth=game.paddle.w;root.dataset.lives=game.lives; root.dataset.gameState = game.running ? (game.paused ? 'paused' : 'running') : (game.lives === 0 ? 'game-over' : game.bricks.length&&game.bricks.every(b=>!b.hp)?'won':'ready'); };
  const makeBricks = () => { game.bricks = []; const cols = 9; const rows = 5; const gap = 7; const bw = (W - 52 - gap * (cols - 1)) / cols; for (let row = 0; row < rows; row += 1) for (let col = 0; col < cols; col += 1) game.bricks.push({ x: 26 + col * (bw + gap), y: 44 + row * 25, w: bw, h: 16, hp: row < 2 ? 2 : 1, hue: row * 30 + col * 4 }); };
  const resetBall = () => { const speed = 235 * Number(difficulty.value); game.ball = { x: W / 2, y: 330, r: 7, vx: speed * (Math.random() > .5 ? 1 : -1), vy: -speed }; game.paddle.x = 270; game.trail = []; };
  const reset = () => { cancelAnimationFrame(game.raf); game.raf = 0; game.score = 0; game.lives = 3; game.running = false; game.paused = false; game.frames = 0; game.particles = []; makeBricks(); resetBall(); updateData(); startButton.disabled = false; pauseButton.disabled = true; setStatus('Ready when you are.'); draw(); };
  const burst = (x, y, hue) => { if (reduced) return; for (let i = 0; i < 12 && game.particles.length < MAX_PARTICLES; i += 1) { const a = Math.random() * Math.PI * 2; const speed = 25 + Math.random() * 100; game.particles.push({ x, y, vx: Math.cos(a) * speed, vy: Math.sin(a) * speed, life: .45 + Math.random() * .35, hue }); } };
  const resize = () => { const rect = canvas.getBoundingClientRect(); const dpr = Math.min(devicePixelRatio || 1, 2); canvas.width = W * dpr; canvas.height = H * dpr; canvas.style.aspectRatio = `${W}/${H}`; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); game.width = W; game.height = H; draw(); };
  const draw = () => { ctx.clearRect(0, 0, W, H); const bg = ctx.createLinearGradient(0, 0, W, H); bg.addColorStop(0, '#0b1225'); bg.addColorStop(1, '#12152b'); ctx.fillStyle = bg; ctx.fillRect(0, 0, W, H); ctx.strokeStyle = '#a9dfd614'; ctx.lineWidth = 1; for (let x = 0; x < W; x += 32) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke(); } game.trail.forEach((p, i) => { ctx.globalAlpha = (i / game.trail.length) * .25; ctx.fillStyle = '#a9dfd6'; ctx.beginPath(); ctx.arc(p.x, p.y, 3 + i / 12, 0, Math.PI * 2); ctx.fill(); }); ctx.globalAlpha = 1; game.bricks.forEach((b) => { if (!b.hp) return; const color = `hsl(${b.hue}, 65%, ${b.hp === 2 ? 72 : 66}%)`; ctx.shadowColor = color; ctx.shadowBlur = 12; ctx.fillStyle = color; ctx.beginPath(); ctx.roundRect(b.x, b.y, b.w, b.h, 5); ctx.fill(); ctx.shadowBlur = 0; }); game.particles.forEach((p) => { ctx.globalAlpha = clamp(p.life * 2, 0, 1); ctx.fillStyle = `hsl(${p.hue}, 80%, 72%)`; ctx.fillRect(p.x, p.y, 3, 3); }); ctx.globalAlpha = 1; ctx.shadowColor = '#a9dfd6'; ctx.shadowBlur = 18; ctx.fillStyle = '#dffcf5'; ctx.beginPath(); ctx.roundRect(game.paddle.x, game.paddle.y, game.paddle.w, game.paddle.h, 6); ctx.fill(); ctx.shadowBlur = 0; ctx.shadowColor = '#aca3df'; ctx.shadowBlur = 22; ctx.fillStyle = '#fff'; ctx.beginPath(); ctx.arc(game.ball.x, game.ball.y, game.ball.r, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; };
  const end = (won) => { game.running = false; game.paused = false; cancelAnimationFrame(game.raf); game.raf = 0; game.best = Math.max(game.best, game.score); updateData(); startButton.disabled = false; pauseButton.disabled = true; setStatus(won ? 'Field cleared — excellent signal.' : 'Signal lost — restart to try again.'); draw(); };
  const update = (now) => { game.raf = 0; if (!game.running || game.paused || game.hidden || disposed) return; const dt = Math.min((now - game.last) / 1000 || 0, .032); game.last = now; game.frames += 1; const ball = game.ball; const oldX = ball.x; const oldY = ball.y; ball.x += ball.vx * dt; ball.y += ball.vy * dt; const speed = 235 * Number(difficulty.value); if (ball.x < ball.r) { ball.x = ball.r; ball.vx = Math.abs(ball.vx); } if (ball.x > W - ball.r) { ball.x = W - ball.r; ball.vx = -Math.abs(ball.vx); } if (ball.y < ball.r) { ball.y = ball.r; ball.vy = Math.abs(ball.vy); } if (ball.vy > 0 && circleHitsRect(ball, game.paddle)) { ball.y = game.paddle.y - ball.r; ball.vy = -Math.abs(ball.vy); ball.vx = clamp(ball.vx + (ball.x - (game.paddle.x + game.paddle.w / 2)) * 3, -speed * 1.5, speed * 1.5); } for (const brick of game.bricks) { if (!brick.hp || !circleHitsRect(ball, brick)) continue; const fromTop = oldY + ball.r <= brick.y; const fromBottom = oldY - ball.r >= brick.y + brick.h; if(fromTop){ball.y=brick.y-ball.r;ball.vy=-Math.abs(ball.vy);}else if(fromBottom){ball.y=brick.y+brick.h+ball.r;ball.vy=Math.abs(ball.vy);}else if(oldX<brick.x+brick.w/2){ball.x=brick.x-ball.r;ball.vx=-Math.abs(ball.vx);}else{ball.x=brick.x+brick.w+ball.r;ball.vx=Math.abs(ball.vx);} brick.hp -= 1; game.score += brick.hp ? 15 : 30; burst(ball.x, ball.y, brick.hue); break; } if (game.bricks.every((b) => !b.hp)) { end(true); return; } if (ball.y - ball.r > H) { game.lives -= 1; if (game.lives <= 0) { end(false); return; } resetBall(); setStatus(`${game.lives} lives remain. Keep the rhythm.`); } if (!reduced) { game.trail.push({ x: ball.x, y: ball.y }); if (game.trail.length > 12) game.trail.shift(); game.particles.forEach((p) => { p.x += p.vx * dt; p.y += p.vy * dt; p.vy += 90 * dt; p.life -= dt; }); game.particles = game.particles.filter((p) => p.life > 0); } draw(); updateData(); game.raf = requestAnimationFrame(update); };
  const start = () => { if (game.running) return; if (game.lives <= 0 || game.bricks.every((b) => !b.hp)) reset(); game.running = true; game.paused = false; startButton.disabled = true; pauseButton.disabled = false; setStatus('In play.'); game.last = performance.now(); updateData(); game.raf = requestAnimationFrame(update); canvas.focus({ preventScroll: true }); };
  const pause = () => { if (!game.running) return; game.paused = !game.paused; if (game.paused) { cancelAnimationFrame(game.raf); game.raf = 0; setStatus('Paused.'); } else { game.last = performance.now(); setStatus('In play.'); game.raf = requestAnimationFrame(update); } updateData(); };
  const move = (clientX) => { const rect = canvas.getBoundingClientRect(); game.paddle.x = clamp((clientX - rect.left) / rect.width * W - game.paddle.w / 2, 0, W - game.paddle.w); draw(); };
  const onPointer = (event) => { move(event.clientX); if (event.type === 'pointerdown') canvas.setPointerCapture?.(event.pointerId); };
  const onKey = (event) => { if (!['ArrowLeft', 'ArrowRight', 'a', 'd', 'A', 'D'].includes(event.key)) return; event.preventDefault(); game.paddle.x = clamp(game.paddle.x + (event.key === 'ArrowLeft' || event.key.toLowerCase() === 'a' ? -34 : 34), 0, W - game.paddle.w); draw(); };
  const onVisibility = () => { game.hidden = document.hidden; if (game.hidden && game.running && !game.paused) { game.paused = true; setStatus('Paused while hidden.'); updateData(); } };
  const onResize = () => resize();let priorDifficulty=Number(difficulty.value);const onDifficulty=()=>{const next=Number(difficulty.value),ratio=next/priorDifficulty;game.ball.vx*=ratio;game.ball.vy*=ratio;priorDifficulty=next;};difficulty.addEventListener('change',onDifficulty);
  canvas.addEventListener('pointermove', onPointer); canvas.addEventListener('pointerdown', onPointer); canvas.addEventListener('keydown', onKey); startButton.addEventListener('click', start); pauseButton.addEventListener('click', pause); root.querySelector('[data-restart]').addEventListener('click', reset); document.addEventListener('visibilitychange', onVisibility); addEventListener('resize', onResize);
  makeBricks(); resetBall(); resize(); updateData();
  return () => { disposed = true;root.dataset.disposed='true';difficulty.removeEventListener('change',onDifficulty); cancelAnimationFrame(game.raf); canvas.removeEventListener('pointermove', onPointer); canvas.removeEventListener('pointerdown', onPointer); canvas.removeEventListener('keydown', onKey); startButton.removeEventListener('click', start); pauseButton.removeEventListener('click', pause); root.querySelector('[data-restart]').removeEventListener('click', reset); document.removeEventListener('visibilitychange', onVisibility); removeEventListener('resize', onResize); root.remove(); };
}
