import './pathfinder.css';

const DEFAULT_COLS = 26;
const DEFAULT_ROWS = 16;
const key = (x, y, cols) => y * cols + x;
const neighbors = (index, cols, rows) => { const x = index % cols; const y = Math.floor(index / cols); return [[x + 1, y], [x - 1, y], [x, y + 1], [x, y - 1]].filter(([nx, ny]) => nx >= 0 && ny >= 0 && nx < cols && ny < rows).map(([nx, ny]) => key(nx, ny, cols)); };

export function searchGrid({ cols, rows, walls = new Set(), start = 0, end = cols * rows - 1, algorithm = 'astar' }) {
  if(walls.has(start)||walls.has(end))return {visited:[],path:[],distance:null,explored:0,found:false};
  const open = [{ index: start, priority: 0 }];
  const cameFrom = new Map(); const cost = new Map([[start, 0]]); const visited = [];
  const heuristic = (index) => Math.abs((index % cols) - (end % cols)) + Math.abs(Math.floor(index / cols) - Math.floor(end / cols));
  while (open.length) {
    open.sort((a, b) => a.priority - b.priority);
    const current = open.shift().index;
    if (visited.includes(current)) continue;
    visited.push(current);
    if (current === end) break;
    neighbors(current, cols, rows).forEach((next) => {
      if (walls.has(next) || visited.includes(next)) return;
      const nextCost = (cost.get(current) ?? Infinity) + 1;
      if (nextCost < (cost.get(next) ?? Infinity)) { cost.set(next, nextCost); cameFrom.set(next, current); open.push({ index: next, priority: nextCost + (algorithm === 'astar' ? heuristic(next) : 0) }); }
    });
  }
  const path = []; if (cost.has(end)) { let current = end; while (current !== undefined) { path.unshift(current); current = cameFrom.get(current); } }
  return { visited, path, distance: path.length ? path.length - 1 : null, explored: visited.length, found: path.length > 0 };
}

function makeMaze(cols, rows) { const walls = new Set(); for (let y = 2; y < rows - 2; y += 2) for (let x = 2 + (y % 4 ? 0 : 2); x < cols - 2; x += 1) walls.add(key(x, y, cols)); for (let y = 1; y < rows - 1; y += 4) walls.delete(key(Math.floor(cols * 0.52), y, cols)); return walls; }
function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }

export function mount(host) {
  if (!(host instanceof HTMLElement)) throw new TypeError('pathfinder.mount(host) expects an HTMLElement');
  const root = document.createElement('section'); root.className = 'pathfinder-demo'; root.setAttribute('aria-labelledby', 'pathfinder-demo-title');
  root.innerHTML = `<header class="pathfinder-demo__header"><div><p class="pathfinder-demo__eyebrow">Search lab / deterministic routing</p><h2 id="pathfinder-demo-title">Find a way through</h2><p>Draw an obstruction, then watch two classic graph searches disagree about how much ground to cover.</p></div><span data-path-status role="status" aria-live="polite">Ready · 0 explored</span></header><div class="pathfinder-demo__board-wrap"><canvas data-path-canvas tabindex="0" aria-label="Pathfinding grid. Use pointer or arrow keys to select cells. Space applies the selected editing tool. S is start and E is finish."></canvas></div><div class="pathfinder-demo__controls"><label>Algorithm <select data-path-algorithm aria-label="Search algorithm"><option value="astar">A* · guided</option><option value="dijkstra">Dijkstra · exhaustive</option></select></label><label>Tool <select data-path-tool aria-label="Grid editing tool"><option value="wall">Draw walls</option><option value="erase">Erase walls</option><option value="start">Move start</option><option value="end">Move finish</option></select></label><button type="button" data-path-run>Run search</button><button type="button" data-path-maze>Example maze</button><button type="button" data-path-reset>Reset</button><span class="pathfinder-demo__metrics"><b>Explored <i data-explored>0</i></b><b>Route <i data-distance>—</i></b></span></div><p class="pathfinder-demo__hint">Draw or place endpoints with the selected tool. Shift/right-drag erases. Keyboard: arrows select a cell; Space applies the tool. S = start, E = finish.</p>`;
  host.replaceChildren(root);
  const canvas = root.querySelector('[data-path-canvas]'); const ctx = canvas.getContext('2d'); const status = root.querySelector('[data-path-status]'); const exploredReadout = root.querySelector('[data-explored]'); const distanceReadout = root.querySelector('[data-distance]'); const algorithm = root.querySelector('[data-path-algorithm]');const tool=root.querySelector('[data-path-tool]');let disposed=false,frames=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
  const state = { cols: DEFAULT_COLS, rows: DEFAULT_ROWS, start: key(1, 8, DEFAULT_COLS), end: key(DEFAULT_COLS - 2, 8, DEFAULT_COLS), walls: new Set(), visited: [], path: [], running: false, searched:false,cursor:key(1,8,DEFAULT_COLS),frame: 0, step: 0, routeStep: 0, erase: false, width: 1, height: 1, cell: 1 };
  const resize = () => { const rect = canvas.getBoundingClientRect(); state.width = Math.max(280, rect.width); state.height = Math.max(210, rect.height); state.cell = Math.min(state.width / state.cols, state.height / state.rows); canvas.width = Math.round(state.width * Math.min(2,devicePixelRatio||1)); canvas.height = Math.round(state.height * Math.min(2,devicePixelRatio||1)); draw(); };
  const cellAt = (event) => { const rect = canvas.getBoundingClientRect(); return { x: clamp(Math.floor((event.clientX - rect.left) / rect.width * state.cols), 0, state.cols - 1), y: clamp(Math.floor((event.clientY - rect.top) / rect.height * state.rows), 0, state.rows - 1) }; };
  const draw = () => { const sx = canvas.width / state.width; ctx.setTransform(sx, 0, 0, sx, 0, 0); ctx.fillStyle = '#080f1c'; ctx.fillRect(0, 0, state.width, state.height); const cellW = state.width / state.cols; const cellH = state.height / state.rows; const visited = new Set(state.visited.slice(0, state.step)); const route = new Set(state.path.slice(0, state.routeStep)); for (let y = 0; y < state.rows; y += 1) for (let x = 0; x < state.cols; x += 1) { const index = key(x, y, state.cols); let color = (x + y) % 2 ? '#0d1828' : '#101d2e'; if (state.walls.has(index)) color = '#27344a'; if (visited.has(index)) color = '#23424c'; if (route.has(index)) color = '#8a7dbf'; if (index === state.start) color = '#a9dfd6'; if (index === state.end) color = '#d6a9dd'; ctx.fillStyle = color; ctx.fillRect(x * cellW + 1, y * cellH + 1, cellW - 2, cellH - 2);if(index===state.start||index===state.end){ctx.fillStyle='#101827';ctx.font=`bold ${Math.max(8,Math.min(cellW,cellH)*.62)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(index===state.start?'S':'E',(x+.5)*cellW,(y+.5)*cellH);}if(index===state.cursor&&document.activeElement===canvas){ctx.strokeStyle='#ffffff';ctx.lineWidth=2;ctx.strokeRect(x*cellW+2,y*cellH+2,cellW-4,cellH-4);} } };
  const updateMetrics = () => {root.dataset.frames=String(frames);root.dataset.running=String(state.running);root.dataset.walls=String(state.walls.size);root.dataset.start=String(state.start);root.dataset.end=String(state.end);root.dataset.algorithm=algorithm.value;root.dataset.found=String(state.searched&&state.path.length>0);root.dataset.distance=state.path.length?String(state.path.length-1):''; exploredReadout.textContent = String(Math.min(state.step, state.visited.length)); distanceReadout.textContent = state.path.length ? String(state.path.length - 1) : '—'; status.textContent = state.running ? `Searching ${algorithm.value === 'astar' ? 'A*' : 'Dijkstra'} · ${Math.min(state.step, state.visited.length)} explored` : state.path.length ? `Route found · ${state.path.length - 1} steps` : state.searched?`No route · ${state.visited.length} cells explored`:`Ready · ${state.walls.size} walls`; };
  const animate = () => { state.frame = 0; if (disposed||!state.running || document.hidden) return;frames++; state.step = Math.min(state.visited.length, state.step + 6); if (state.step >= state.visited.length) state.routeStep = Math.min(state.path.length, state.routeStep + 2); draw(); updateMetrics(); if (state.routeStep < state.path.length || state.step < state.visited.length) state.frame = requestAnimationFrame(animate); else { state.running = false; updateMetrics(); } };
  const run = () => { if (state.frame) cancelAnimationFrame(state.frame); const result = searchGrid({ cols: state.cols, rows: state.rows, walls: state.walls, start: state.start, end: state.end, algorithm: algorithm.value }); state.visited = result.visited; state.path = result.path; state.step = 0; state.routeStep = 0; state.searched=true;state.running = true;if(reduced.matches){state.step=state.visited.length;state.routeStep=state.path.length;state.running=false;draw();updateMetrics();return;} status.textContent = `Searching ${algorithm.value === 'astar' ? 'A*' : 'Dijkstra'}…`; state.frame = requestAnimationFrame(animate); };
  const reset = () => { if (state.frame) cancelAnimationFrame(state.frame); state.walls.clear();state.start=key(1,8,state.cols);state.end=key(state.cols-2,8,state.cols);state.cursor=state.start;state.searched=false; state.visited = []; state.path = []; state.running = false; state.step = 0; state.routeStep = 0; draw(); updateMetrics(); };
  const maze = () => { reset(); state.walls = makeMaze(state.cols, state.rows); draw(); updateMetrics(); };
  const invalidate=()=>{cancelAnimationFrame(state.frame);state.frame=0;state.running=false;state.searched=false;state.visited=[];state.path=[];state.step=0;state.routeStep=0;};
  const applyCell=index=>{invalidate();if(tool.value==='start'&&!state.erase){if(index!==state.end){state.start=index;state.walls.delete(index);}}else if(tool.value==='end'&&!state.erase){if(index!==state.start){state.end=index;state.walls.delete(index);}}else if(index!==state.start&&index!==state.end){if(state.erase||tool.value==='erase')state.walls.delete(index);else state.walls.add(index);}draw();updateMetrics();};
  const paint=event=>{const {x,y}=cellAt(event);state.cursor=key(x,y,state.cols);applyCell(state.cursor);};
  const onPointerDown = (event) => { event.preventDefault();canvas.focus({preventScroll:true}); state.erase = event.button === 2 || event.shiftKey; canvas.setPointerCapture?.(event.pointerId); paint(event); }; const onPointerMove = (event) => { if (event.buttons) { state.erase = event.buttons === 2 || event.shiftKey; paint(event); } }; const onContext = (event) => event.preventDefault();
  const onKey=event=>{if(event.key===' '||event.key==='Enter'){event.preventDefault();state.erase=event.shiftKey;applyCell(state.cursor);return;}if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const x=state.cursor%state.cols,y=Math.floor(state.cursor/state.cols);state.cursor=key(clamp(x+(event.key==='ArrowRight'?1:event.key==='ArrowLeft'?-1:0),0,state.cols-1),clamp(y+(event.key==='ArrowDown'?1:event.key==='ArrowUp'?-1:0),0,state.rows-1),state.cols);draw();};
  const onVisibility = () => { if (document.hidden && state.frame) { cancelAnimationFrame(state.frame); state.frame = 0; }else if(!document.hidden&&state.running&&!state.frame){state.frame=requestAnimationFrame(animate);} };
  const onAlgorithm=()=>{invalidate();draw();updateMetrics();};algorithm.addEventListener('change',onAlgorithm);
  canvas.addEventListener('pointerdown', onPointerDown); canvas.addEventListener('pointermove', onPointerMove); canvas.addEventListener('contextmenu', onContext); canvas.addEventListener('keydown', onKey); window.addEventListener('resize', resize); document.addEventListener('visibilitychange', onVisibility); root.querySelector('[data-path-run]').addEventListener('click', run); root.querySelector('[data-path-maze]').addEventListener('click', maze); root.querySelector('[data-path-reset]').addEventListener('click', reset); resize(); reset();
  return () => { disposed=true;root.dataset.disposed='true';algorithm.removeEventListener('change',onAlgorithm);if (state.frame) cancelAnimationFrame(state.frame); canvas.removeEventListener('pointerdown', onPointerDown); canvas.removeEventListener('pointermove', onPointerMove); canvas.removeEventListener('contextmenu', onContext); canvas.removeEventListener('keydown', onKey); window.removeEventListener('resize', resize); document.removeEventListener('visibilitychange', onVisibility); root.remove(); };
}
